### ISSUE TITLE
DB 연결 정보 파일의 부재

### ISSUE THREAD

**Issue by HoJeongKimmm** [CSID-DGU/2024-1-OSSProj-DevOops-02#12]
Database 연결에 대한 정보를 갖고 있는 application.yml 파일이 ignore로 설정되어 있어서 프로젝트를 가져오면서 DB 연결 정보가 사라짐

**Comment by HoJeongKimmm** [comment]
직접 yml 파일과 MySQLWorkbench를 통해 테스트용 Database를 생성해서 문제 해결
```
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: ****


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

```
